FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
  gcc \
  default-libmysqlclient-dev \
  pkg-config \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY .env .

# Expose port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "src.main_api:app", "--host", "0.0.0.0", "--port", "8000"]
